-- ~/.config/nvim/ftplugin/typescript.lua
-- LSP configurado em lua/plugins/nvim-lspconfig.lua
-- Formatação via conform.nvim (<leader>l) com prettier
-- Autocompletar configurado globalmente em lua/plugins/nvim-cmp.lua
